scan_timeout = 50

[custom.chezmoi]
when = 'test -n "$CHEZMOI"'
shell = ["sh", "--noprofile" , "--norc"]
symbol = 'ğŸ¡'

[kubernetes]
disabled = false
detect_env_vars = [ 'KUBIE_ACTIVE' ]
symbol = 'âš“ '
